
  name: Validate YAML
  # You may pin to the exact commit or the version.
  # uses: brittonhayes/validate-yaml@7039dd2e9ab1840a5d0934ae0ad3fa4c9c03ff5f
  on:
   push:
    branches: [main]
   pull_request:
    branches: [main]
  jobs:
   validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nrkno/yaml-schema-validator-github-action@v4
      with:
        schema: schema/schema.yml
        target: example/valid.yml
    - uses: IceflowRE/gitcc@v2
      with:
       validator: 'RegEx'
       options: '[a-z]'
       access_token: ''
        # Uncomment to disable strict checks
        # no-strict: true
  

      
    # - uses: brittonhayes/validate-yaml@v0.5.1
    #   name: validate yaml file 
    #   with:
    # # Files to validate
    #    schemaPath: schema/schema.json
    #    files: |
    #       example/*.yml
